export const TYPES = {
    // Template
    ACTION_TEMPLATE_SET_SELECTED_TEMPLATE: "ACTION_TEMPLATE_SET_SELECTED_TEMPLATE",
    
    ACTION_TEMPLATE_GET_TEMPLATE_DATA_SUCCESSFUL: "ACTION_TEMPLATE_GET_TEMPLATE_DATA_SUCCESSFUL",
    ACTION_TEMPLATE_GET_MARKDOWN_DATA_SUCCESSFUL: "ACTION_TEMPLATE_GET_MARKDOWN_DATA_SUCCESSFUL",
    ACTION_TEMPLATE_GET_STYLE_DATA_SUCCESSFUL: "ACTION_TEMPLATE_GET_STYLE_DATA_SUCCESSFUL",
    ACTION_TEMPLATE_GET_CONFIG_DATA_SUCCESSFUL: "ACTION_TEMPLATE_GET_CONFIG_DATA_SUCCESSFUL",
    
    ACTION_TEMPLATE_UPDATE_MARKDOWN: "ACTION_TEMPLATE_UPDATE_MARKDOWN",
    ACTION_TEMPLATE_UPDATE_STYLE: "ACTION_TEMPLATE_UPDATE_STYLE",

    ACTION_TEMPLATE_GENERATE_SVG: "ACTION_TEMPLATE_GENERATE_SVG"
}